Fixes
jordanspooner/ic-first-year-notes pull request #5
Opened 2017-04-21 17:04 UTC by Qiang-Feng

2017-04-25 15:59 UTC, lsquires commented
Great moves Qiang, proud of you, keep it up!

2017-04-26 13:54 UTC, lsquires approved these changes
10/10
would commit

2017-04-26 13:54 UTC, lsquires commented on 112.tex
> +Multiplication by 2 is equivalent to a left shift, so for 2 bits:
Nice

2017-05-07 22:14 UTC, jordanspooner requested changes
I don't think an explanation of adjacent state assignments is necessary. Does it add an extra line? If so, we'll need to reword it again.

2017-05-07 22:15 UTC, jordanspooner approved these changes
Otherwise, all good. Thanks, Qiang!

2017-05-07 22:21 UTC, merged